### ISSUE TITLE
求教个实时率问题

### ISSUE THREAD

**Issue by Cosjimmy** [Z-yq/TensorflowTTS#1]
求教一下大佬用的是什么样的计算机？ 实时率指比如我用tacotron 生成一个10s的语音，生成时间会在1秒左右吗？ 我tacotron和fast speech都试过了 但合成都在7，8秒左右 不知道问题出在哪了

**Comment by Z-yq** [comment]
你可以循环多次合成看看时间，因为只是简单的设置了 @tf.function() 所以，它需要3次预合成。性能才能体现。

**Comment by Cosjimmy** [comment]
感谢感谢！
